---
title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true
---



-------------------     
722 W 168th St, 
New York, NY 10032, 
United States
-------------------     



Education
---------

Sep 2019 - Apr 2021 

* **Columbia University**  
  * *Master of Science in Epidemiology*


Sep 2011 - May 2015 

* **Dartmouth College**  
  * *Bachelor of Arts in Neuroscience*

Experience
----------

May 2020 - Aug 2020

* **COVID-19 Research & Project Officer** - International Institute of Rural Reconstruction (IIRR)
  * Led creation of strategic partnerships with development consultancies and impact investors for the Rural Response Fund 

Nov 2016 - May 2018

* **Project Operations Lead** - AiCure
  * Managed day-to-day operational deliverables during execution of more than ten clinical trials and population health projects

Aug 2015 - Nov 2016

* **Clinical Research Coordinator I & II** - Massachusetts General Hospital (MGH)
  * Performed retrospective analysis of metastatic melanoma patients undergoing cancer immunotherapy treatment (ipilimumab) to
identify potential risk factors for drug-induced gastrointestinal toxicities

Publications
--------------------

* Shafner, L. & Chah, Y. (2018). **Using Artificial Intelligence Platforms to Enhance Study Design in Schizophrenia Trials.** Poster presented
at the 6th biennial Schizophrenia International Research Society Conference, Florence, Italy.

* Walsh, E. R., Chah, Y., Chin, S. M., Lochhead, P., Yajnik, V., Denmark, V. K., Garber, J., & Khalili, H. (2017). **Clinical Predictors and
Natural History of Disease Extension in Patients with Ulcerative Proctitis.** Inflammatory Bowel Diseases, 23(11), 2035-2041.


Hobbies
----------------------------------------

* Avid indoor rock climber!
