---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
runtime: shiny
---

```{r setup, include = FALSE}

library(tidyverse)
library(p8105.datasets)
library(plotly)
library(flexdashboard)

```

```{r}
data(rest_inspec)

korean_df = rest_inspec %>%
            filter(str_detect(cuisine_description, "Korean"))

```

Column {data-width=550}
-----------------------------------------------------------------------
### Chart A

```{r}

korean_df %>%
  filter(dba %in% c("DANJI", "JONGRO BBQ", "CHO DANG GOL", "GAMMEEOK", "TAKE 31")) %>%
  plot_ly(x = ~dba, y = ~score, color = ~dba, type = "box", colors =   "viridis") %>%
  layout(title = "Distribution of scores for Chloe's favorite Korean restaurants", xaxis = list(title ="Restaurant name"), yaxis = list(title="Score"))


```


Column {data-width=450}
-----------------------------------------------------------------------
### Chart B

```{r}

korean_df %>%
  drop_na(score) %>%
  sample_n(1000) %>%
  group_by(grade_date, boro, dba) %>%
  summarise(avg_score = mean(score)) %>%
  plot_ly(x = ~grade_date, y = ~avg_score, type = "scatter", mode = "line", color = ~boro, colors = "viridis") %>%
  layout(title = "Avg.score of Korean restaurants by boro", xaxis = list(title ="Date"), yaxis = list(title="Average score"))

```


### Chart C

```{r}

korean_df %>%
  mutate(boro = fct_infreq(boro)) %>%
  group_by(boro, grade) %>%
  summarise(count = n()) %>%
  plot_ly(x = ~boro, y = ~count, color = ~grade, type = "bar", colors = "viridis") %>%
  layout(title = "Distribution of grades for Korean restaurants by boro", xaxis = list(title ="Borough"), yaxis = list(title="Count", range = c(0,1000)))


```
